- name: install
  hosts: gandi
  handlers:
  tasks:
    - name: Update sshd Configuration
      ansible.builtin.template:
        src: system-tree/default/tree/etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "0600"
        validate: /usr/sbin/sshd -t -f %s
        backup: yes
      notify: Restart ssh service

    - name: Set authorized key for root
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'system-tree/default/tree/root/.ssh/id_rsa.pub') }}"
        key_options: ""
        exclusive: yes

    - name: Set authorized key for {{ username }}
      ansible.posix.authorized_key:
        user: { { username } }
        state: present
        key: "{{ lookup('file', 'system-tree/default/tree/root/.ssh/id_rsa.pub') }}"
        key_options: ""
        exclusive: yes

    - name: Registering files to copy
      set_fact:
        homeUserFiles:
          - system-tree/default/tree/root/.bash_profile
          - system-tree/default/tree/root/.bashrc
          - system-tree/default/tree/root/.gitconfig
          - system-tree/default/tree/root/.inputrc
          - system-tree/default/tree/root/.profile
          - system-tree/default/tree/root/.psqlrc
    - name: Print the find_result
      ansible.builtin.debug:
        msg: "{{ homeUserFiles }}"

    - name: Copy files root home files
      vars:
        username: root
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /root
        owner: root
        group: root
        mode: u=rw,g=-rwx,o=-rwx
        backup: yes
      loop: "{{ homeUserFiles }}"

    - name: Copy {{ username }} user config files
      vars:
        username: "{{ username }}"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /home/{{ username }}
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: u=rw,g=r,o=r
        backup: yes
      loop: "{{ homeUserFiles }}"

    - name: Synchronizing etc/network using rsync delegating to host (push)
      ansible.posix.synchronize:
        src: system-tree/default/tree/etc/network/
        dest: /etc/network/
      delegate_to: localhost

    - name: Create git user
      user:
        name: git
        shell: /usr/bin/git-shell
        home: /srv/git
        system: yes
    - name: Add SSH key to git user
      authorized_key:
        user: git
        key: "{{ lookup('file', 'system-tree/default/tree/root/.ssh/id_rsa.pub') }}"
        state: present
    - name: Initialize bare repository
      command: git init --bare --shared=group /srv/git/ansible.git
      args:
        creates: /srv/git/ansible.git/HEAD
      become_user: git
