---
- ansible.builtin.include_role:
    name: git-repo
  when: git_user_configured is not defined or not git_user_configured
- name: Initialize bare repository
  command: git init --bare --shared=group /srv/git/ansible.git
  args:
    creates: /srv/git/ansible.git/HEAD
  become_user: git
  when: git_user_configured is defined and git_user_configured
