---
- name: Create git user
  user:
    name: git
    password: "*"
    shell: /usr/bin/git-shell
    home: /srv/git
    system: yes
- name: Add SSH key to git user
  authorized_key:
    user: git
    key: "{{ lookup('file', '../../common/templates/root/.ssh/id_rsa.pub') }}"
    state: present
- name: GitUserConfigured
  ansible.builtin.set_fact:
    git_user_configured: true
