#!/bin/bash
# /etc/network/if-post-down.d/iptables-stop
# Script qui réinitialise les règles de filtrage "iptables"
# Formation Debian GNU/Linux par Alexis de Lattre
# http://www.via.ecp.fr/~alexis/formation-linux/

# REMISE à ZERO des règles de filtrage
iptables -F
iptables -t nat -F
