- name: install
  hosts: gandi
  vars:
    old_username: debian
    new_username: pi
  tasks:
    - name: Initialize bare repository
      command: git init --bare --shared=group /srv/git/ansible.git
      args:
        creates: /srv/git/ansible.git/HEAD
      become: yes
      become_user: git
