all:
  hosts:
    piprime.fr:
      ansible_host: server1.piprime.fr
      ansible_port: 201
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_2025
      old_username: debian
      new_username: pi
      node_version: 20
      webdav_login: '{{ lookup(''ansible.builtin.pipe'', "pass webdav.piprime.fr | grep ''login:'' | awk ''{print $2}''") }}'
      webdav_password: '{{ lookup(''ansible.builtin.pipe'', "pass webdav.piprime.fr | head -1") }}'
      webdav_directory: "/srv/webdav" ## Needed for role caddy-webdav
  children:
    git_repo:
      hosts: piprime.fr
    caddy-docker-webdav:
      hosts: piprime.frx
