- name: apt all
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - git
          - rsync
          - htop
          - nano
          - locales
          - fonts-powerline
          - powerline-gitstatus
          - tree
          - exa
          - delta
          - iptables
          - nmap
          - gpg
          - gpg
        state: latest
