---
- name: Add Caddy GPG key
  ansible.builtin.apt_key:
    url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
    state: present

- name: Add Caddy repository
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
