- name: Install the latest version of Node.js
  hosts: all
  become: yes
  vars:
    version: 20
  tasks:
    - name: Add Node.js PPA
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js repository
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_{{ version }}.x {{ ansible_distribution_release }} main
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: latest

    - name: Verify Node.js installation
      ansible.builtin.command: node --version
      register: node_version

    - name: Display Node.js version
      ansible.builtin.debug:
        msg: "Node.js version installed: {{ node_version.stdout }}"
