---
- name: Create directory for caddy-docker-proxy
  ansible.builtin.file:
    path: /opt/caddy-webdav
    state: directory
    mode: "0755"

- name: Create Caddyfile template
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /opt/caddy-webdav/Caddyfile

- name: Create Docker WebDAV directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  with_items:
    - /opt/caddy-webdav/data
    - /opt/caddy-webdav/config
    - /srv/webdav

- name: Create Docker Compose file
  ansible.builtin.copy:
    content: |
      services:
        caddy_webdav:
          image: juvenn/caddy-dav:2.7.6
          container_name: caddy_webdav
          restart: always
          volumes:
            - /opt/caddy-webdav/Caddyfile:/etc/caddy/Caddyfile:ro
            - /srv/webdav:/srv
            - /opt/caddy-webdav/data:/data
            - /opt/caddy-webdav/config:/config
          networks:
            - caddy
          labels:
            caddy: webdav.{{ inventory_hostname }}
            caddy.reverse_proxy: {% raw %}"{{ upstreams 809 }}"{% endraw %}

      networks:
        caddy:
          external: true

    dest: /opt/caddy-webdav/docker-compose.yml

- name: Run Docker Compose
  command: docker compose up -d
  args:
    chdir: /opt/caddy-webdav
