---
- name: Create Caddyfile template
  template:
    src: Caddyfile.j2
    dest: /opt/caddy-webdav/Caddyfile

- name: Create WebDAV directory
  file:
    path: /srv/webdav
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Create Docker Compose file
  copy:
    content: |
      version: '3.8'

      services:
        caddy_webdav:
          image: caddy:2
          container_name: caddy_webdav
          restart: always
          volumes:
            - /opt/caddy-webdav/Caddyfile:/etc/caddy/Caddyfile
            - /srv/webdav:/srv
          networks:
            - caddy
          labels:
            caddy: webdav.{{ inventory_hostname }}
             caddy.reverse_proxy: {% raw %}"{{upstreams 80}}"{% endraw %}

      networks:
        caddy:
          external: true
    dest: /opt/caddy-webdav/docker-compose.yml

- name: Run Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/caddy-webdav
