---
- name: Create WebDAV directory
  ansible.builtin.file:
    path: "{{ webdav_directory }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: RestartCaddy

- name: Ensure Caddy service is enabled and started
  ansible.builtin.service:
    name: caddy
    state: started
    enabled: yes
