---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    state: latest
- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
