---
- name: Download Node.js GPG key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /usr/share/keyrings/nodesource-archive-keyring.gpg
    mode: "0644"

- name: Add Node.js repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: latest

- name: Verify Node.js installation
  ansible.builtin.command: node --version
  register: node_version_cmd

- name: Display Node.js version
  ansible.builtin.debug:
    msg: "Node.js version installed: {{ node_version_cmd.stdout }}"
