---
- name: Include password setting fact "rpassword"
  include_tasks: password.yml
- name: Ensure the user {{ new_username }} exists
  ansible.builtin.user:
    name: "{{ new_username }}"
    password: "{{ rpassword | password_hash('sha512') }}"
    groups: sudo
    state: present
    create_home: yes
    shell: /bin/bash
- name: Ensure the {{ new_username }} user has sudo privileges without password
  ansible.builtin.copy:
    content: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ new_username }}"
    owner: root
    group: root
    mode: "0440"
