---
- name: Registering files to copy
  set_fact:
    homeUserFiles:
      - ../templates/root/.bash_profile
      - ../templates/root/.bashrc
      - ../templates/root/.gitconfig
      - ../templates/root/.inputrc
      - ../templates/root/.profile
      - ../templates/root/.psqlrc
- name: Print the Home User Files
  ansible.builtin.debug:
    msg: "{{ homeUserFiles }}"

- name: Copy files root home files
  vars:
    username: root
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /root
    owner: root
    group: root
    mode: u=rw,g=-rwx,o=-rwx
    backup: yes
  loop: "{{ homeUserFiles }}"

- name: Copy user {{ username }} config files
  vars:
    username: "{{ username }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /home/{{ username }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u=rw,g=r,o=r
    backup: yes
  loop: "{{ homeUserFiles }}"
  when: new_username is defined
