---
- name: Configure all servers
  hosts: all
  roles:
    - common
- name: Configure Caddy web servers
  hosts: webserver_caddy
  roles:
    - webserver-caddy
# - name: Configure WebDAV servers with Caddy
#   hosts: webdav_caddy
#   roles:
#     - webdav-caddy
# - name: Configure Git servers
#   hosts: git_repo
#   roles:
#     - git-repo
# - name: Specific tasks on piprime.fr
#   import_playbook: piprime.fr/main.yml
