---
- name: Configure all servers
  hosts: all
  roles:
    - common
- name: Configure Caddy web servers
  hosts: caddy_webserver
  roles:
    - caddy-webserver
- name: Configure WebDAV servers with Caddy
  hosts: caddy_webdav
  roles:
    - caddy-webdav
- name: Configure Git servers
  hosts: git_repo
  roles:
    - git-repo
- name: Configure Caddy Docker Webdav
  hosts: caddy_docker_webdav
  roles:
    - caddy-docker-webdav
- name: Specific tasks on piprime.fr
  import_playbook: piprime.fr/main.yml
