- name: Rename old_username to new_username
  hosts: all
  tasks:
    - name: ../roles/common/tasks/user-rename.yml
      include_tasks: ../roles/common/tasks/user-rename.yml
      when: old_username is defined and new_username is defined
