- name: Create new_default_user
  hosts: all
  tasks:
    - name: ../roles/common/tasks/user-create.yml
      include_tasks: ../roles/common/tasks/user-create.yml
      when: old_default_user is not defined and new_default_user is defined
