- name: Create new_username
  hosts: all
  become: yes
  tasks:
    - name: ../roles/commun/tasks/user-create.yml
      include_tasks: ../roles/commun/tasks/user-create.yml
      when: old_username is not defined and new_username is defined
