- name: Rename {{ old_username }} to {{ new_username }}
  hosts: all
  become: yes
  tasks:
    - name: ../roles/commun/tasks/user-rename.yml
      include_tasks: ../roles/commun/tasks/user-rename.yml
